"use client";
import React from "react";
import { motion } from "framer-motion";
import { 
  Users, 
  IndianRupee, 
  Briefcase, 
  GraduationCap, 
  Building2, 
  TrendingUp, 
  FileCheck, 
  MessageSquare, 
  Share2, 
  Award,
  CheckCircle2
} from "lucide-react";
import SectionLabel from "../SectionLabel";

// Define card layouts and data
interface MetricItem {
  id: number;
  value: string;
  label: string;
  category: string;
  gridSpan: string; // Tailwind grid span classes
  icon: React.ReactNode;
  bgGlow?: string;
  visualDetail?: React.ReactNode;
}

export default function CohortMetrics() {
  const metrics: MetricItem[] = [
    {
      id: 1,
      value: "80+",
      label: "Members Across Cohort 01",
      category: "COMMUNITY",
      gridSpan: "col-span-12 md:col-span-4",
      icon: <Users className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.03)",
      visualDetail: (
        <div className="mt-6 flex flex-wrap gap-2 items-center">
          <div className="flex -space-x-3">
            {[1, 2, 3, 4, 5].map((idx) => (
              <div 
                key={idx} 
                className="w-8 h-8 rounded-full border-2 border-black bg-neutral-900 flex items-center justify-center text-[9px] font-bold text-white/60"
                style={{
                  backgroundImage: `linear-gradient(135deg, #1e1e1e 0%, #2d2d2d 100%)`
                }}
              >
                M0{idx}
              </div>
            ))}
          </div>
          <span className="text-[10px] text-white/40 uppercase tracking-widest pl-2">Cohort Active</span>
        </div>
      )
    },
    {
      id: 2,
      value: "₹12 Lakhs+",
      label: "Revenue Generated by Members",
      category: "OUTCOME",
      gridSpan: "col-span-12 md:col-span-4",
      icon: <IndianRupee className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.08)",
      visualDetail: (
        <div className="mt-4 space-y-2">
          <div className="flex justify-between text-[10px] text-white/40 uppercase tracking-wider">
            <span>Progress to Target</span>
            <span className="text-[#F3D7A7]">120% achieved</span>
          </div>
          <div className="w-full h-1.5 bg-white/5 rounded-full overflow-hidden">
            <motion.div 
              initial={{ width: 0 }}
              whileInView={{ width: "100%" }}
              viewport={{ once: true }}
              transition={{ duration: 1, ease: "easeOut" }}
              className="h-full bg-gradient-to-r from-[#F3D7A7]/40 via-[#F3D7A7] to-[#F3D7A7]/50 rounded-full" 
            />
          </div>
        </div>
      )
    },
    {
      id: 3,
      value: "30+",
      label: "Members Landed Their First Client",
      category: "SUCCESS",
      gridSpan: "col-span-12 md:col-span-4",
      icon: <Briefcase className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.03)",
      visualDetail: (
        <div className="mt-4 grid grid-cols-2 gap-2 text-[10px] text-white/50 uppercase tracking-widest font-semibold">
          <div className="flex items-center gap-1.5 px-2 py-1.5 bg-white/5 rounded border border-white/5">
            <CheckCircle2 className="w-3.5 h-3.5 text-[#F3D7A7]" /> Upwork
          </div>
          <div className="flex items-center gap-1.5 px-2 py-1.5 bg-white/5 rounded border border-white/5">
            <CheckCircle2 className="w-3.5 h-3.5 text-[#F3D7A7]" /> LinkedIn
          </div>
        </div>
      )
    },
    {
      id: 4,
      value: "20+",
      label: "Students Placed",
      category: "CAREERS",
      gridSpan: "col-span-12 md:col-span-3",
      icon: <GraduationCap className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.02)",
      visualDetail: (
        <div className="mt-3 flex gap-2">
          <div className="text-[10px] bg-neutral-900 border border-white/10 px-2 py-1 rounded text-white/60">Creative</div>
          <div className="text-[10px] bg-neutral-900 border border-white/10 px-2 py-1 rounded text-white/60">Marketing</div>
        </div>
      )
    },
    {
      id: 5,
      value: "10+",
      label: "Agencies Hiring Through BIC",
      category: "PARTNERS",
      gridSpan: "col-span-12 md:col-span-3",
      icon: <Building2 className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.02)",
      visualDetail: (
        <div className="mt-3 flex items-center justify-between text-[10px] text-white/40 font-semibold tracking-wider">
          <span>VETTED PARTNERS</span>
          <span className="flex h-2 w-2 relative">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
          </span>
        </div>
      )
    },
    {
      id: 6,
      value: "5+",
      label: "Businesses Started",
      category: "ENTREPRENEURSHIP",
      gridSpan: "col-span-12 md:col-span-6",
      icon: <TrendingUp className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.04)",
      visualDetail: (
        <div className="mt-3 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-t border-white/5 pt-4">
          <div className="flex gap-4">
            <div>
              <div className="text-[10px] text-white/40 uppercase">Incubated</div>
              <div className="text-white font-bold text-sm">₹2.4L avg/mo</div>
            </div>
            <div className="border-l border-white/10 pl-4">
              <div className="text-[10px] text-white/40 uppercase">Domain</div>
              <div className="text-[#F3D7A7] font-bold text-sm">Media & SaaS</div>
            </div>
          </div>
          <div className="text-[10px] bg-[#F3D7A7]/10 text-[#F3D7A7] border border-[#F3D7A7]/20 px-3 py-1.5 rounded-full font-bold uppercase tracking-wider self-start sm:self-center">
            BIC Incubator
          </div>
        </div>
      )
    },
    {
      id: 7,
      value: "260+",
      label: "Portfolio Reviews",
      category: "FEEDBACK",
      gridSpan: "col-span-12 md:col-span-3",
      icon: <FileCheck className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.02)",
      visualDetail: (
        <div className="mt-3 text-[10px] text-white/40 font-mono flex items-center justify-between">
          <span>COMPLETED SUCCESFULLY</span>
          <span className="text-[#F3D7A7]">100%</span>
        </div>
      )
    },
    {
      id: 8,
      value: "700+",
      label: "Outreach Messages Reviewed",
      category: "OUTREACH",
      gridSpan: "col-span-12 md:col-span-3",
      icon: <MessageSquare className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.02)",
      visualDetail: (
        <div className="mt-3 text-[10px] text-white/50 bg-white/5 px-2.5 py-1.5 rounded border border-white/5 font-mono overflow-hidden whitespace-nowrap text-ellipsis">
          Subject: Collaboration proposal...
        </div>
      )
    },
    {
      id: 9,
      value: "50+",
      label: "Collaboration Opportunities",
      category: "NETWORKING",
      gridSpan: "col-span-12 md:col-span-3",
      icon: <Share2 className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.02)",
      visualDetail: (
        <div className="mt-4 flex -space-x-1.5">
          {[1, 2, 3].map((v) => (
            <div key={v} className="w-5 h-5 rounded-full bg-white/10 border border-black flex items-center justify-center text-[7px] font-bold text-white/70">
              C{v}
            </div>
          ))}
          <div className="w-5 h-5 rounded-full bg-[#F3D7A7]/20 border border-black flex items-center justify-center text-[7px] font-bold text-[#F3D7A7]">
            +
          </div>
        </div>
      )
    },
    {
      id: 10,
      value: "20+",
      label: "Internship Offers",
      category: "DEVELOPMENT",
      gridSpan: "col-span-12 md:col-span-3",
      icon: <Award className="w-5 h-5 text-[#F3D7A7]" />,
      bgGlow: "rgba(243, 215, 167, 0.02)",
      visualDetail: (
        <div className="mt-4 flex items-center gap-1.5 text-[10px] text-[#F3D7A7] uppercase tracking-wider font-semibold">
          <Award className="w-3.5 h-3.5" /> Paid internships
        </div>
      )
    }
  ];

  return (
    <section className="py-32 px-6 md:px-24 bg-black text-white relative z-20 overflow-hidden">
      
      {/* Decorative Fluid Lines & Glowing Background (Masters' Union Inspired) */}
      <div className="absolute inset-0 z-0 pointer-events-none overflow-hidden opacity-40">
        {/* Swirling Yellow/Orange Glow Elements */}
        <div className="absolute top-[20%] left-[-10%] w-[50%] h-[40%] rounded-full bg-gradient-to-tr from-[#F3D7A7]/10 via-[#F3D7A7]/5 to-transparent blur-[120px] transform -rotate-12" />
        <div className="absolute bottom-[10%] right-[-10%] w-[45%] h-[50%] rounded-full bg-gradient-to-bl from-[#F3D7A7]/8 via-[#F3D7A7]/3 to-transparent blur-[140px] transform rotate-45" />
        
        {/* Soft Fluid Vector Lines (using CSS border/gradient arcs) */}
        <div className="absolute top-[15%] right-[10%] w-[600px] h-[600px] rounded-full border-t border-r border-[#F3D7A7]/10 opacity-30 blur-[2px] pointer-events-none" />
        <div className="absolute bottom-[5%] left-[5%] w-[800px] h-[800px] rounded-full border-b border-l border-[#F3D7A7]/5 opacity-20 blur-[3px] pointer-events-none" />
        
        {/* Decorative gold trail line */}
        <svg 
          className="absolute top-0 left-0 w-full h-full opacity-20 pointer-events-none hidden md:block" 
          viewBox="0 0 1440 800" 
          fill="none" 
          xmlns="http://www.w3.org/2000/svg"
        >
          <path 
            d="M-50,650 C200,600 400,200 700,450 C1000,700 1200,150 1500,100" 
            stroke="url(#goldGradient)" 
            strokeWidth="2" 
            strokeLinecap="round"
          />
          <defs>
            <linearGradient id="goldGradient" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stopColor="#F3D7A7" stopOpacity="0" />
              <stop offset="50%" stopColor="#F3D7A7" stopOpacity="0.4" />
              <stop offset="100%" stopColor="#F3D7A7" stopOpacity="0" />
            </linearGradient>
          </defs>
        </svg>
      </div>

      <div className="max-w-7xl mx-auto relative z-10">
        {/* Section Header */}
        <div className="max-w-3xl mb-20 text-left">
          <SectionLabel light>Outcomes & Impact</SectionLabel>
          <motion.h2 
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="text-5xl md:text-8xl font-black uppercase tracking-tight leading-[0.85] text-left text-white"
          >
            BIC by the <br />
            <span className="text-white/20">Numbers.</span>
          </motion.h2>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="mt-6 text-white/50 text-lg leading-relaxed max-w-xl text-left"
          >
            The hard proof of what happens when ambitious creators execute built-for-market systems. No fluff, just real outcomes.
          </motion.p>
        </div>

        {/* Bento Grid */}
        <div className="grid grid-cols-12 gap-5 auto-rows-fr">
          {metrics.map((item, index) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.05 }}
              whileHover={{ 
                y: -6,
                borderColor: "rgba(243, 215, 167, 0.4)",
                backgroundColor: "rgba(10, 10, 11, 0.85)",
                transition: { duration: 0.3 }
              }}
              style={{
                backgroundColor: "rgba(10, 10, 11, 0.65)",
                boxShadow: item.id === 2 ? "0 0 40px rgba(243, 215, 167, 0.03)" : "none"
              }}
              className={`p-8 md:p-10 flex flex-col justify-between border ${item.id === 2 ? 'border-[#F3D7A7]/25' : 'border-white/10'} rounded-3xl backdrop-blur-2xl transition-all duration-300 overflow-hidden relative group text-left ${item.gridSpan}`}
            >
              {/* Soft card inner glow */}
              <div 
                className="absolute -top-12 -right-12 w-32 h-32 rounded-full blur-3xl opacity-30 group-hover:opacity-60 transition-opacity duration-500 pointer-events-none"
                style={{ backgroundColor: item.id === 2 ? "rgba(243, 215, 167, 0.15)" : "rgba(255, 255, 255, 0.04)" }}
              />
              
              <div>
                {/* Top bar with category and icon */}
                <div className="flex items-center justify-between mb-8">
                  <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/30 group-hover:text-[#F3D7A7]/60 transition-colors duration-300">
                    {item.category}
                  </span>
                  <div className="p-2 border border-white/5 bg-white/[0.02] rounded-xl group-hover:border-[#F3D7A7]/20 group-hover:bg-[#F3D7A7]/5 transition-all duration-300">
                    {item.icon}
                  </div>
                </div>

                {/* Main Stat & Label */}
                <div className="space-y-3">
                  <div className="flex items-baseline">
                    <span 
                      className={`text-4xl md:text-5xl lg:text-6xl font-black tracking-tight leading-none ${
                        item.id === 2 
                          ? "bg-gradient-to-r from-white via-[#F3D7A7] to-white/90 bg-clip-text text-transparent drop-shadow-[0_0_20px_rgba(243,215,167,0.15)]" 
                          : "text-white group-hover:text-[#F3D7A7] transition-colors duration-300"
                      }`}
                    >
                      {item.value}
                    </span>
                  </div>
                  <h3 className="text-white/70 text-sm md:text-base font-bold uppercase tracking-wide leading-snug max-w-[90%]">
                    {item.label}
                  </h3>
                </div>
              </div>

              {/* Graphic/Visual Detail if present */}
              {item.visualDetail && (
                <div className="relative z-10">
                  {item.visualDetail}
                </div>
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
